# Generated by Django 3.2.13 on 2022-06-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='UserComment',
        ),
    ]
